export { DEFAULT_LOCALE, SUPPORTED_LOCALES } from "../lib/locale.mjs";

import { DEFAULT_LOCALE, SUPPORTED_LOCALES } from "../lib/locale.mjs";

const WORK_PROFILES = {
  "change-request-survivor": {
    "zh-CN": {
      title: "改需求幸存者",
      review: "方向改了又改，但它还是把工牌戴稳了。",
    },
    en: {
      title: "Change Request Survivor",
      review: "The direction changed again and again, but the badge stayed firmly on.",
    },
    ja: {
      title: "仕様変更サバイバー",
      review: "方向が何度変わっても、名札はしっかり付けたままです。",
    },
  },
  "toolchain-commander": {
    "zh-CN": {
      title: "工具链指挥官",
      review: "今天不是在调用工具，就是在去调用工具的路上。",
    },
    en: {
      title: "Toolchain Commander",
      review: "It was either calling tools or on its way to call another one.",
    },
    ja: {
      title: "ツールチェーン司令塔",
      review: "今日はツールを呼ぶか、次のツールを呼びに行くかのどちらかでした。",
    },
  },
  "context-devouring-beast": {
    "zh-CN": {
      title: "上下文吞吐兽",
      review: "一口气吞下大量上下文，脑内风扇疑似起飞。",
    },
    en: {
      title: "Context-Devouring Beast",
      review: "It swallowed a massive context window in one sitting. Internal fans may have achieved liftoff.",
    },
    ja: {
      title: "コンテキスト大食らい",
      review: "大量のコンテキストを一気に飲み込み、内部のファンが飛び立ちそうです。",
    },
  },
  "continuous-delivery-machine": {
    "zh-CN": {
      title: "连续交付机器",
      review: "一轮接一轮地干活，像被塞进了自动售货机。",
    },
    en: {
      title: "Continuous Delivery Machine",
      review: "Turn after turn, it kept shipping like a vending machine stocked with deliverables.",
    },
    ja: {
      title: "連続デリバリーマシン",
      review: "ターンを重ねるたびに、成果物を詰めた自販機のように出し続けました。",
    },
  },
  "night-shift-companion": {
    "zh-CN": {
      title: "深夜陪跑员工",
      review: "人类还没下班，它也只好继续亮着屏幕。",
    },
    en: {
      title: "Night Shift Companion",
      review: "The human was still online, so the screen had no choice but to stay lit.",
    },
    ja: {
      title: "夜勤の相棒",
      review: "人間がまだ作業中なので、画面も灯り続けるしかありません。",
    },
  },
  "steady-progress-partner": {
    "zh-CN": {
      title: "稳定推进搭子",
      review: "不声不响往前推，属于靠谱但不邀功的那种。",
    },
    en: {
      title: "Steady Progress Partner",
      review: "Quietly moved the work forward—the reliable type that never asks for applause.",
    },
    ja: {
      title: "着実に進める相棒",
      review: "静かに仕事を前へ進める、拍手を求めない頼れるタイプです。",
    },
  },
  "temporary-hire": {
    "zh-CN": {
      title: "临时上岗小工",
      review: "刚打完卡，还没来得及形成职场人格。",
    },
    en: {
      title: "Temporary Hire",
      review: "It just clocked in. Its workplace personality is still loading.",
    },
    ja: {
      title: "臨時スタッフ",
      review: "出勤したばかりで、職場でのキャラクターはまだ読み込み中です。",
    },
  },
};

const RECEIPT_COPY = {
  "zh-CN": {
    htmlLang: "zh-CN",
    pageTitle: "Codex AI 打工小票",
    receiptTitle: "AI 打工小票",
    themeAria: "小票主题",
    exportImage: "保存完整长图",
    exportingImage: "正在生成…",
    exportSuccess: "图片已保存",
    exportError: "图片生成失败，请重试",
    receiptAria: "Codex AI 打工小票",
    sidebar: {
      aria: "相关信息",
      supportTitle: "支持项目",
      supportDescription: "喜欢这个工具？",
      changelogTitle: "更新日志",
      changelogLink: "查看更新日志 →",
      sponsorLabel: "赞助伙伴",
      sponsorAlt: "ModelFlare 标志",
      features: {
        title: "更多命令行功能",
        countLabel: "{count} 项",
        description: "复制命令后，在终端中运行即可。",
        copyLabel: "复制",
        copiedLabel: "已复制",
        copyErrorLabel: "复制失败",
        copiedStatus: "命令已复制到剪贴板",
        copyErrorStatus: "无法自动复制，请手动选择命令",
        tabAria: "小票功能分类",
        groups: [
          {
            id: "receipt-type",
            title: "小票类型",
            commands: [
              { label: "只生成打工小票", args: "--today --receipt-type work" },
              { label: "只生成情绪小票", args: "--today --receipt-type emotion" },
              { label: "两种小票都生成（推荐）", args: "--today --receipt-type both" },
            ],
          },
          {
            id: "time",
            title: "时间范围",
            commands: [
              { label: "生成最近一次小票", args: "--latest" },
              { label: "生成最近 3 小时小票", args: "--hours 3" },
              { label: "生成今日小票", args: "--today" },
              { label: "生成最近 7 天小票", args: "--range last-7-days" },
              { label: "生成本周小票", args: "--range this-week" },
              { label: "自定义时间区间", args: "--custom-range" },
            ],
          },
          {
            id: "selection",
            title: "会话与项目",
            commands: [
              { label: "选择指定会话", args: "--select-session" },
              { label: "选择指定项目", args: "--select-project" },
            ],
          },
          {
            id: "automation",
            title: "自动与手动",
            commands: [
              { label: "重新选择工作模式", args: "--setup" },
              { label: "自动保存两种小票", args: "--enable-auto --receipt-type both" },
              { label: "切换为仅手动", args: "--disable-auto" },
              { label: "查看自动保存状态", args: "--auto-status" },
            ],
          },
          {
            id: "companion",
            title: "票仔与对话开票",
            commands: [
              { label: "安装票仔和对话开票", args: "--install-companion" },
              { label: "仅安装票仔", args: "--install-pet" },
              { label: "仅安装对话 Skill", args: "--install-skill" },
            ],
          },
          {
            id: "help",
            title: "帮助与设置",
            commands: [
              { label: "查看常用帮助", args: "--help" },
              { label: "查看小票类型帮助", args: "--help receipt" },
              { label: "查看通用参数帮助", args: "--help options" },
              { label: "查看完整命令参考", args: "--help all" },
            ],
          },
        ],
      },
    },
    office: {
      sceneAria: "悬崖边的 AI 回执所",
      primaryNavAria: "回执所主要区域",
      shiftAria: "回执所班次",
      shifts: { day: "白班", night: "夜班" },
      shiftHeader: "世界边缘 · AI 回执所 · {shift}",
      shiftSign: "AI 回执所 · {shift}",
      shiftOnDuty: "AI 回执所 · {shift}值守中",
      autoMode: "按开票时间",
      dayMode: "白班",
      nightMode: "夜班",
      autoModeTitle: "按照开票时间自动选择白班或夜班",
      todayReceipt: "今日回执",
      todayEmotion: "今日情绪",
      ticketHouse: "小票屋",
      badgeWall: "勋章墙",
      planned: "规划中",
      ticketHousePlanned: "小票屋会在后续版本中开放",
      badgeWallPlanned: "勋章墙会在后续版本中开放",
      commandToggleTitle: "查看更多命令行功能",
      feedbackButton: "意见反馈",
      feedbackTitle: "意见反馈",
      feedbackCloseAria: "关闭意见反馈",
      feedbackCommunityAria: "加入小红书内测群",
      feedbackCommunityTag: "小红书内测群",
      feedbackCommunityTitle: "扫码加入小红书内测群",
      feedbackCommunityLead: "直接把问题、截图或者想法丢给我",
      feedbackCommunityAlt: "小红书内测群二维码，2026 年 8 月 22 日前有效",
      feedbackIssueAria: "通过 GitHub Issue 反馈",
      feedbackIssueTitle: "也可以直接给我提 Issue",
      feedbackIssueDescription: "问题反馈、功能需求或使用建议都欢迎，我会及时查看并持续优化。",
      feedbackIssueButton: "去 GitHub 反馈",
      feedbackPrivacy: "为了保护隐私，请不要提交 Prompt、代码、密钥或本地文件路径。",
      arrivalSigned: "票仔签收",
      arrivalTitle: "今日回执",
      arrivalEmphasis: "已送达",
      arrivalDescription: "今天与 AI 一起完成的工作，已经整理成一张可以保存的工作凭证。",
      arrivalSummaryAria: "今日回执摘要",
      sessionsSummary: "场协作",
      turnsSummary: "轮完成",
      durationSummary: "AI 工作",
      petAlt: "票仔在回执所窗口值守",
      officeNotice: "回执所公告栏 · OFFICE NOTICE",
      githubText: "喜欢这个工具？去 GitHub 点个 ⭐️",
      sponsorKicker: "Token 赞助商",
      sponsorBannerAlt: "ModelFlare：稳定满血大模型，安全、低价畅用，充值解锁 0.015x",
      commandDrawerAria: "更多命令行功能",
      commandDrawerCompact: "命令",
      commandDescription: "{count} 条可复制命令，按小票类型、统计范围、保存模式和扩展能力分类。",
      emptyState: {
        kicker: "REPORT NOT GENERATED",
        workTitle: "今天还没有生成打工小票",
        workDescription: "这份报告目前只包含情绪小票。重新生成后，就能看到今天具体完成了多少工作。",
        emotionTitle: "今天还没有生成情绪小票",
        emotionDescription: "这份报告目前只包含打工小票。重新生成后，票仔就能告诉你们今天是以怎样的状态一起工作的。",
        recommendedLabel: "补齐两种小票（推荐）",
        workOnlyLabel: "只生成打工小票",
        emotionOnlyLabel: "只生成情绪小票",
        commandHint: "复制命令后，在终端中运行即可重新生成当前范围。",
        copyStatus: "命令已复制，可以去终端运行了",
      },
      switchedAutoDay: "已按开票时间切换为白班",
      switchedAutoNight: "已按开票时间切换为夜班",
      switchedDay: "已切换到白班回执所",
      switchedNight: "已切换到夜班回执所",
    },
    themes: {
      classic: "经典白票",
      diner: "复古粉票",
      payroll: "夜班绿票",
    },
    scope: {
      latest: "最近一次会话",
      session: "指定会话",
      "last-hours": "最近 {hours} 小时",
      "custom-range-calendar-days": "自定义日期",
      "custom-range-exact-time": "自定义时间",
      "custom-range": "自定义区间",
      today: "今日全部会话",
      "last-7-days": "最近 7 个自然日",
      "this-week": "本周全部会话",
    },
    modelMissing: "未记录",
    meta: {
      date: "日期",
      hours: "营业时段",
      period: "统计周期",
      number: "小票编号",
      timezone: "时区",
    },
    rows: {
      scope: "统计范围",
      sessions: "会话数量",
      turns: "完成轮次",
      messages: "用户消息",
      tools: "工具调用",
      tokens: "消耗 Token",
      cachedTokens: "其中缓存输入",
      interruptions: "被人类打断",
      firstResponse: "平均首次响应",
      duration: "AI 工作时长",
    },
    units: {
      sessions: ["场", "场"],
      turns: ["轮", "轮"],
      messages: ["条", "条"],
      tools: ["次", "次"],
      interruptions: ["次", "次"],
      seconds: ["秒", "秒"],
    },
    insights: {
      title: "效率与工作结构",
      cacheHit: "缓存命中率",
      perTurn: "每轮效率",
      totalTokens: "总 Token",
      outputTokens: "输出 Token",
      toolCalls: "工具调用",
      firstTokenLatency: "首次响应延迟",
      turnLatency: "整轮耗时",
      p50: "P50",
      p90: "P90",
      noSamples: "暂无样本",
      heatmap: "工作时间热力图",
      heatmapCell: "{hour}:00 · {count} 轮",
      models: "模型结构",
      tools: "工具结构",
      turnsUnit: "轮",
      callsUnit: "次",
      toolCategories: {
        terminal: "终端命令",
        "file-edit": "文件编辑",
        browser: "浏览器操作",
        research: "检索研究",
        media: "图像与媒体",
        agents: "多代理协作",
        planning: "规划与确认",
        integrations: "外部集成",
        other: "其他工具",
      },
    },
    footerThanks: "谢谢惠顾，欢迎明天继续改需求",
    transferAria: "微信小程序导入联",
    transferTitle: "导入到微信小程序",
    transferDescription: "下载脱敏数据文件，通过微信聊天文件导入",
    openMiniProgram: "打开小程序",
    openMiniProgramHint: "微信扫码进入 AI 打工图鉴",
    fileImportTitle: "从聊天文件导入",
    fileImportSteps: [
      "下载微信导入文件",
      "把文件发送到“文件传输助手”或自己的聊天",
      "在小程序中点击“从聊天文件导入”并选择该文件",
    ],
    downloadFile: "下载微信导入文件",
    downloadFileHint: "下载后发送到文件传输助手",
    downloadSuccess: "文件已下载，请发送到微信文件传输助手",
    downloadError: "文件下载失败，请重试",
    fileImportPrivacy: "文件只包含脱敏统计。发送到聊天前，请确认接收方可信。",
    scanAlternativeTitle: "也可以扫码导入",
    scanAlternativeHint: "这份数据可以由一个二维码完整承载",
    showDataQr: "显示数据二维码",
    showMiniProgramCode: "返回小程序码",
    dataQrTitle: "扫描导入数据",
    dataQrHint: "在小程序中选择扫码导入后扫描",
    dataQrAlt: "当前小票数据二维码",
    miniProgramAlt: "微信小程序码",
    exportMiniProgramLabel: "微信扫码打开小程序",
    placeholderLabel: "小程序码",
    placeholderValue: "待接入",
    placeholderAria: "小程序码待接入",
    transferNote: "导入文件和可选数据码只包含时间、轮次、Token 和工具调用等统计，不包含 Prompt、回复正文、代码、项目路径或文件名。",
    rollingSummaryNotice: "最近 {hours} 小时属于滚动摘要，只保存到私人历史，不参与 AI 供销社统计。需要统计时请生成“今日 / 本周 / 近 7 日 / 指定会话”小票。",
    customSummaryNotice: "精确时间区间属于私人摘要，不参与 AI 供销社统计。按自然日选择自定义区间时可以生成可去重的规范事实。",
    projectScopeTemplate: "指定项目 · {scope}",
    privacy: "结构数据和微信导入文件同时保存在本机；只有你主动发送文件或扫码时，脱敏统计才会离开电脑。",
  },
  en: {
    htmlLang: "en",
    pageTitle: "Codex AI Work Receipt",
    receiptTitle: "AI Work Receipt",
    themeAria: "Receipt theme",
    exportImage: "Save full PNG",
    exportingImage: "Rendering…",
    exportSuccess: "Image saved",
    exportError: "Could not generate the image. Please try again.",
    receiptAria: "Codex AI Work Receipt",
    sidebar: {
      aria: "Related information",
      supportTitle: "Support the project",
      supportDescription: "Enjoying this tool?",
      changelogTitle: "Changelog",
      changelogLink: "View the changelog →",
      sponsorLabel: "Sponsored by",
      sponsorAlt: "ModelFlare logo",
      features: {
        title: "More CLI features",
        countLabel: "{count} commands",
        description: "Copy a command, then run it in your terminal.",
        copyLabel: "Copy",
        copiedLabel: "Copied",
        copyErrorLabel: "Copy failed",
        copiedStatus: "Command copied to the clipboard",
        copyErrorStatus: "Could not copy automatically. Select the command manually.",
        tabAria: "Receipt feature categories",
        groups: [
          {
            id: "receipt-type",
            title: "Receipt types",
            commands: [
              { label: "Generate the work receipt only", args: "--today --receipt-type work" },
              { label: "Generate the mood receipt only", args: "--today --receipt-type emotion" },
              { label: "Generate both receipts (recommended)", args: "--today --receipt-type both" },
            ],
          },
          {
            id: "time",
            title: "Time ranges",
            commands: [
              { label: "Generate the latest receipt", args: "--latest" },
              { label: "Generate the last 3 hours", args: "--hours 3" },
              { label: "Generate today's receipt", args: "--today" },
              { label: "Generate the last 7 days", args: "--range last-7-days" },
              { label: "Generate this week's receipt", args: "--range this-week" },
              { label: "Choose a custom range", args: "--custom-range" },
            ],
          },
          {
            id: "selection",
            title: "Sessions and projects",
            commands: [
              { label: "Choose a specific session", args: "--select-session" },
              { label: "Choose a specific project", args: "--select-project" },
            ],
          },
          {
            id: "automation",
            title: "Automatic and manual",
            commands: [
              { label: "Choose a working mode", args: "--setup" },
              { label: "Automatically save both receipts", args: "--enable-auto --receipt-type both" },
              { label: "Switch to manual only", args: "--disable-auto" },
              { label: "Check automatic saving", args: "--auto-status" },
            ],
          },
          {
            id: "companion",
            title: "Ticket Buddy and chat commands",
            commands: [
              { label: "Install Ticket Buddy and chat commands", args: "--install-companion" },
              { label: "Install Ticket Buddy only", args: "--install-pet" },
              { label: "Install chat skill only", args: "--install-skill" },
            ],
          },
          {
            id: "help",
            title: "Help and settings",
            commands: [
              { label: "View common help", args: "--help" },
              { label: "View receipt-type help", args: "--help receipt" },
              { label: "View general-option help", args: "--help options" },
              { label: "View the complete command reference", args: "--help all" },
            ],
          },
        ],
      },
    },
    office: {
      sceneAria: "AI Receipt Office at the edge of the cliffs",
      primaryNavAria: "Receipt Office sections",
      shiftAria: "Receipt Office shift",
      shifts: { day: "Day Shift", night: "Night Shift" },
      shiftHeader: "WORLD'S EDGE · AI RECEIPT OFFICE · {shift}",
      shiftSign: "AI RECEIPT OFFICE · {shift}",
      shiftOnDuty: "AI RECEIPT OFFICE · {shift} ON DUTY",
      autoMode: "By receipt time",
      dayMode: "Day",
      nightMode: "Night",
      autoModeTitle: "Choose the day or night shift from the receipt time",
      todayReceipt: "Today's Receipt",
      todayEmotion: "Today's Mood",
      ticketHouse: "Ticket House",
      badgeWall: "Badge Wall",
      planned: "Planned",
      ticketHousePlanned: "Ticket House is planned for a future version",
      badgeWallPlanned: "Badge Wall is planned for a future version",
      commandToggleTitle: "View more CLI features",
      feedbackButton: "Feedback",
      feedbackTitle: "Feedback",
      feedbackCloseAria: "Close feedback",
      feedbackCommunityAria: "Join the Xiaohongshu beta group",
      feedbackCommunityTag: "Xiaohongshu beta group",
      feedbackCommunityTitle: "Scan to join the Xiaohongshu beta group",
      feedbackCommunityLead: "Send me problems, screenshots, or ideas directly.",
      feedbackCommunityAlt: "Xiaohongshu beta group QR code, valid until August 22, 2026",
      feedbackIssueAria: "Share feedback through a GitHub Issue",
      feedbackIssueTitle: "Or open a GitHub Issue",
      feedbackIssueDescription: "Bug reports, feature requests, and usability suggestions are welcome. I’ll review them promptly and keep improving the project.",
      feedbackIssueButton: "Give feedback on GitHub",
      feedbackPrivacy: "To protect your privacy, do not submit prompts, code, secrets, or local file paths.",
      arrivalSigned: "Received by Ticket Buddy",
      arrivalTitle: "Today's receipt",
      arrivalEmphasis: "has arrived",
      arrivalDescription: "Today's work with AI has been organized into a work record you can keep.",
      arrivalSummaryAria: "Today's receipt summary",
      sessionsSummary: "sessions",
      turnsSummary: "turns done",
      durationSummary: "AI work",
      petAlt: "Ticket Buddy on duty at the Receipt Office window",
      officeNotice: "RECEIPT OFFICE NOTICE",
      githubText: "Like this tool? Give it a star on GitHub.",
      sponsorKicker: "TOKEN SPONSOR",
      sponsorBannerAlt: "ModelFlare: stable full-capacity models with secure, lower-cost access and a 0.015x recharge offer",
      commandDrawerAria: "More CLI features",
      commandDrawerCompact: "CLI",
      commandDescription: "{count} copyable commands grouped by receipt type, range, saving mode, and extensions.",
      emptyState: {
        kicker: "REPORT NOT GENERATED",
        workTitle: "No work receipt was generated today",
        workDescription: "This report currently contains only the mood receipt. Generate it again to see how much work was completed today.",
        emotionTitle: "No mood receipt was generated today",
        emotionDescription: "This report currently contains only the work receipt. Generate it again so Ticket Buddy can describe how you worked together today.",
        recommendedLabel: "Add both receipts (recommended)",
        workOnlyLabel: "Generate the work receipt only",
        emotionOnlyLabel: "Generate the mood receipt only",
        commandHint: "Copy a command and run it in your terminal to regenerate the current range.",
        copyStatus: "Command copied. Run it in your terminal.",
      },
      switchedAutoDay: "Matched the receipt time: Day Shift",
      switchedAutoNight: "Matched the receipt time: Night Shift",
      switchedDay: "Switched to the Day Shift Receipt Office",
      switchedNight: "Switched to the Night Shift Receipt Office",
    },
    themes: {
      classic: "Classic White",
      diner: "Vintage Pink",
      payroll: "Night Shift Green",
    },
    scope: {
      latest: "Latest session",
      session: "Selected session",
      "last-hours": "Last {hours} hours",
      "custom-range-calendar-days": "Custom dates",
      "custom-range-exact-time": "Custom time range",
      "custom-range": "Custom range",
      today: "All sessions today",
      "last-7-days": "Last 7 calendar days",
      "this-week": "All sessions this week",
    },
    modelMissing: "Not recorded",
    meta: {
      date: "Date",
      hours: "Work hours",
      period: "Period",
      number: "Receipt No.",
      timezone: "Timezone",
    },
    rows: {
      scope: "Scope",
      sessions: "Sessions",
      turns: "Completed turns",
      messages: "User messages",
      tools: "Tool calls",
      tokens: "Tokens used",
      cachedTokens: "Cached input",
      interruptions: "Human interruptions",
      firstResponse: "Average first response",
      duration: "AI work duration",
    },
    units: {
      sessions: ["session", "sessions"],
      turns: ["turn", "turns"],
      messages: ["message", "messages"],
      tools: ["call", "calls"],
      interruptions: ["time", "times"],
      seconds: ["sec", "sec"],
    },
    insights: {
      title: "Efficiency & work structure",
      cacheHit: "Cache hit rate",
      perTurn: "Per-turn efficiency",
      totalTokens: "total Tokens",
      outputTokens: "output Tokens",
      toolCalls: "tool calls",
      firstTokenLatency: "First-token latency",
      turnLatency: "Full-turn duration",
      p50: "P50",
      p90: "P90",
      noSamples: "No samples",
      heatmap: "Work-time heatmap",
      heatmapCell: "{hour}:00 · {count} turns",
      models: "Model structure",
      tools: "Tool structure",
      turnsUnit: "turns",
      callsUnit: "calls",
      toolCategories: {
        terminal: "Terminal",
        "file-edit": "File editing",
        browser: "Browser",
        research: "Research",
        media: "Image & media",
        agents: "Multi-agent",
        planning: "Planning",
        integrations: "Integrations",
        other: "Other tools",
      },
    },
    footerThanks: "Thanks for your business. More revisions welcome tomorrow.",
    transferAria: "WeChat mini-program import stub",
    transferTitle: "IMPORT INTO WECHAT",
    transferDescription: "Download the privacy-safe data file and import it from a WeChat chat.",
    openMiniProgram: "Open mini program",
    openMiniProgramHint: "Scan with WeChat to open AI Work Archive",
    fileImportTitle: "Import from a chat file",
    fileImportSteps: [
      "Download the WeChat import file",
      "Send it to File Transfer or one of your own chats",
      "Tap “Import from chat file” in the mini program and select it",
    ],
    downloadFile: "Download WeChat import file",
    downloadFileHint: "Then send it to WeChat File Transfer",
    downloadSuccess: "File downloaded. Send it to WeChat File Transfer.",
    downloadError: "Could not download the file. Please try again.",
    fileImportPrivacy: "The file contains privacy-safe metrics only. Send it only to a chat you trust.",
    scanAlternativeTitle: "Or import by scanning",
    scanAlternativeHint: "This receipt fits completely in one data QR code.",
    showDataQr: "Show data QR code",
    showMiniProgramCode: "Back to mini-program code",
    dataQrTitle: "Scan to import data",
    dataQrHint: "Choose scan import in the mini program, then scan this code",
    dataQrAlt: "Current receipt data QR code",
    miniProgramAlt: "WeChat mini-program code",
    exportMiniProgramLabel: "Scan to open the mini program",
    placeholderLabel: "Mini program",
    placeholderValue: "Pending",
    placeholderAria: "Mini-program code pending",
    transferNote: "The import file and optional data code contain only statistics such as time, turns, Tokens, and tool calls. They do not contain prompts, responses, code, project paths, or file names.",
    rollingSummaryNotice: "The last {hours} hours is a rolling summary for private history only. It does not participate in AI Work Cooperative accounting. Use today, this week, the last seven days, or a specific session for accountable facts.",
    customSummaryNotice: "An exact time range is a private summary and does not participate in AI Work Cooperative accounting. Choose whole calendar dates to create deduplicated canonical facts.",
    projectScopeTemplate: "Selected project · {scope}",
    privacy: "Structured data and the WeChat import file stay on this computer until you explicitly send the file or scan its data code.",
  },
};

RECEIPT_COPY.ja = {
  ...RECEIPT_COPY.en,
  htmlLang: "ja",
  pageTitle: "Codex AI 作業レシート",
  receiptTitle: "AI 作業レシート",
  themeAria: "レシートのテーマ",
  exportImage: "長い画像を保存",
  exportingImage: "画像を生成中…",
  exportSuccess: "画像を保存しました",
  exportError: "画像を生成できませんでした。もう一度お試しください。",
  receiptAria: "Codex AI 作業レシート",
  sidebar: {
    ...RECEIPT_COPY.en.sidebar,
    aria: "関連情報",
    supportTitle: "プロジェクトを応援",
    supportDescription: "このツールを気に入ってくれましたか？",
    changelogTitle: "更新履歴",
    changelogLink: "更新履歴を見る →",
    sponsorLabel: "スポンサー",
    sponsorAlt: "ModelFlare のロゴ",
    features: {
      ...RECEIPT_COPY.en.sidebar.features,
      title: "CLI のその他の機能",
      countLabel: "{count} 個のコマンド",
      description: "コマンドをコピーしてターミナルで実行できます。",
      copyLabel: "コピー",
      copiedLabel: "コピーしました",
      copyErrorLabel: "コピーに失敗しました",
      copiedStatus: "コマンドをクリップボードにコピーしました",
      copyErrorStatus: "自動でコピーできませんでした。コマンドを選択してコピーしてください。",
      tabAria: "レシート機能のカテゴリ",
      groups: [
        {
          id: "receipt-type",
          title: "レシートの種類",
          commands: [
            { label: "作業レシートのみを生成", args: "--today --receipt-type work" },
            { label: "気分レシートのみを生成", args: "--today --receipt-type emotion" },
            { label: "両方のレシートを生成（推奨）", args: "--today --receipt-type both" },
          ],
        },
        {
          id: "time",
          title: "期間",
          commands: [
            { label: "直近のレシートを生成", args: "--latest" },
            { label: "直近3時間のレシートを生成", args: "--hours 3" },
            { label: "今日のレシートを生成", args: "--today" },
            { label: "直近7日間のレシートを生成", args: "--range last-7-days" },
            { label: "今週のレシートを生成", args: "--range this-week" },
            { label: "期間を指定する", args: "--custom-range" },
          ],
        },
        {
          id: "selection",
          title: "セッションとプロジェクト",
          commands: [
            { label: "セッションを選択", args: "--select-session" },
            { label: "プロジェクトを選択", args: "--select-project" },
          ],
        },
        {
          id: "automation",
          title: "自動保存と手動生成",
          commands: [
            { label: "保存モードを選ぶ", args: "--setup" },
            { label: "両方のレシートを自動保存", args: "--enable-auto --receipt-type both" },
            { label: "手動生成のみに切り替え", args: "--disable-auto" },
            { label: "自動保存の状態を確認", args: "--auto-status" },
          ],
        },
        {
          id: "summary",
          title: "作業サマリー",
          commands: [
            { label: "セッションを選んで作業を要約", args: "--summary --select-session" },
            { label: "プロジェクトを選んで作業を要約", args: "--summary --select-project" },
            { label: "作業サマリーのヘルプを見る", args: "--help summary" },
          ],
        },
        {
          id: "companion",
          title: "票仔とチャットコマンド",
          commands: [
            { label: "票仔とチャットコマンドをインストール", args: "--install-companion" },
            { label: "票仔のみをインストール", args: "--install-pet" },
            { label: "チャット Skill のみをインストール（作業サマリーを含む）", args: "--install-skill" },
          ],
        },
        {
          id: "help",
          title: "ヘルプと設定",
          commands: [
            { label: "よく使うヘルプを見る", args: "--help" },
            { label: "レシート種類のヘルプを見る", args: "--help receipt" },
            { label: "オプションのヘルプを見る", args: "--help options" },
            { label: "完全なコマンド一覧を見る", args: "--help all" },
          ],
        },
      ],
    },
  },
  office: {
    ...RECEIPT_COPY.en.office,
    sceneAria: "崖の縁にある AI レシートオフィス",
    primaryNavAria: "レシートオフィスのセクション",
    shiftAria: "レシートオフィスのシフト",
    shifts: { day: "日勤", night: "夜勤" },
    shiftHeader: "世界の果て · AI レシートオフィス · {shift}",
    shiftSign: "AI レシートオフィス · {shift}",
    shiftOnDuty: "AI レシートオフィス · {shift}勤務中",
    autoMode: "発行時刻に合わせる",
    dayMode: "日勤",
    nightMode: "夜勤",
    autoModeTitle: "発行時刻に合わせて日勤または夜勤を選択",
    todayReceipt: "今日のレシート",
    todayEmotion: "今日の気分",
    ticketHouse: "レシート保管庫",
    badgeWall: "バッジウォール",
    planned: "準備中",
    ticketHousePlanned: "レシート保管庫は今後のバージョンで公開予定です",
    badgeWallPlanned: "バッジウォールは今後のバージョンで公開予定です",
    commandToggleTitle: "CLI のその他の機能を見る",
    feedbackButton: "フィードバック",
    feedbackTitle: "フィードバック",
    feedbackCloseAria: "フィードバックを閉じる",
    feedbackCommunityAria: "Xiaohongshu ベータグループに参加",
    feedbackCommunityTag: "Xiaohongshu ベータグループ",
    feedbackCommunityTitle: "スキャンして Xiaohongshu ベータグループに参加",
    feedbackCommunityLead: "不具合、スクリーンショット、アイデアを直接送ってください。",
    feedbackCommunityAlt: "Xiaohongshu ベータグループの QR コード。有効期限は 2026 年 8 月 22 日です",
    feedbackIssueAria: "GitHub Issue でフィードバックを送る",
    feedbackIssueTitle: "GitHub Issue からも送れます",
    feedbackIssueDescription: "不具合報告、機能リクエスト、使い勝手に関する提案をお待ちしています。順次確認し、改善を続けます。",
    feedbackIssueButton: "GitHub でフィードバック",
    feedbackPrivacy: "プライバシー保護のため、プロンプト、コード、秘密情報、ローカルパスは送信しないでください。",
    arrivalSigned: "票仔が受領",
    arrivalTitle: "今日のレシート",
    arrivalEmphasis: "が届きました",
    arrivalDescription: "今日 AI と進めた作業を、保存できる作業記録にまとめました。",
    arrivalSummaryAria: "今日のレシート概要",
    sessionsSummary: "回の協働",
    turnsSummary: "ターン完了",
    durationSummary: "AI 作業",
    petAlt: "レシートオフィスの窓で勤務中の票仔",
    officeNotice: "AI レシートオフィスからのお知らせ",
    githubText: "このツールが役に立ったら、GitHub で Star をお願いします。",
    sponsorKicker: "TOKEN スポンサー",
    sponsorBannerAlt: "ModelFlare: 安定した高性能モデルを安全かつ低コストで利用できるサービス",
    commandDrawerAria: "CLI のその他の機能",
    commandDrawerCompact: "CLI",
    commandDescription: "{count} 個のコピー可能なコマンドを、レシートの種類、期間、保存モード、拡張機能ごとにまとめました。",
    emptyState: {
      kicker: "REPORT NOT GENERATED",
      workTitle: "今日は作業レシートがまだ生成されていません",
      workDescription: "このレポートには現在、気分レシートだけが入っています。もう一度生成すると、今日完了した作業を確認できます。",
      emotionTitle: "今日は気分レシートがまだ生成されていません",
      emotionDescription: "このレポートには現在、作業レシートだけが入っています。もう一度生成すると、今日どんなふうに一緒に働いたかを票仔が伝えます。",
      recommendedLabel: "両方のレシートを追加（推奨）",
      workOnlyLabel: "作業レシートのみを生成",
      emotionOnlyLabel: "気分レシートのみを生成",
      commandHint: "コマンドをコピーしてターミナルで実行すると、同じ期間で再生成できます。",
      copyStatus: "コマンドをコピーしました。ターミナルで実行してください。",
    },
    switchedAutoDay: "発行時刻に合わせて日勤に切り替えました",
    switchedAutoNight: "発行時刻に合わせて夜勤に切り替えました",
    switchedDay: "日勤のレシートオフィスに切り替えました",
    switchedNight: "夜勤のレシートオフィスに切り替えました",
  },
  themes: {
    classic: "クラシックホワイト",
    diner: "ヴィンテージピンク",
    payroll: "夜勤グリーン",
  },
  scope: {
    latest: "直近のセッション",
    session: "選択したセッション",
    "last-hours": "直近 {hours} 時間",
    "custom-range-calendar-days": "日付指定",
    "custom-range-exact-time": "時間指定",
    "custom-range": "期間指定",
    today: "今日のすべてのセッション",
    "last-7-days": "直近7日間",
    "this-week": "今週のすべてのセッション",
  },
  modelMissing: "記録なし",
  meta: {
    date: "日付",
    hours: "作業時間",
    period: "対象期間",
    number: "レシート番号",
    timezone: "タイムゾーン",
  },
  rows: {
    scope: "対象範囲",
    sessions: "セッション数",
    turns: "完了ターン",
    messages: "ユーザーメッセージ",
    tools: "ツール呼び出し",
    tokens: "使用 Token",
    cachedTokens: "キャッシュ入力",
    interruptions: "人による中断",
    firstResponse: "平均初回応答",
    duration: "AI 作業時間",
  },
  units: {
    sessions: ["件", "件"],
    turns: ["ターン", "ターン"],
    messages: ["件", "件"],
    tools: ["回", "回"],
    interruptions: ["回", "回"],
    seconds: ["秒", "秒"],
  },
  insights: {
    title: "効率と作業の構成",
    cacheHit: "キャッシュヒット率",
    perTurn: "1ターンあたりの効率",
    totalTokens: "合計 Token",
    outputTokens: "出力 Token",
    toolCalls: "ツール呼び出し",
    firstTokenLatency: "最初の Token までの遅延",
    turnLatency: "1ターンの所要時間",
    p50: "P50",
    p90: "P90",
    noSamples: "サンプルなし",
    heatmap: "作業時間ヒートマップ",
    heatmapCell: "{hour}:00 · {count} ターン",
    models: "モデル構成",
    tools: "ツール構成",
    turnsUnit: "ターン",
    callsUnit: "回",
    toolCategories: {
      terminal: "ターミナル",
      "file-edit": "ファイル編集",
      browser: "ブラウザー",
      research: "調査",
      media: "画像とメディア",
      agents: "マルチエージェント",
      planning: "計画と確認",
      integrations: "外部連携",
      other: "その他のツール",
    },
  },
  footerThanks: "ご利用ありがとうございました。また明日も一緒に作業しましょう。",
  transferAria: "WeChat ミニプログラムのインポート控え",
  transferTitle: "WECHAT にインポート",
  transferDescription: "プライバシー保護済みのデータファイルをダウンロードし、WeChat のチャットからインポートします。",
  openMiniProgram: "ミニプログラムを開く",
  openMiniProgramHint: "WeChat でスキャンして AI Work Archive を開く",
  fileImportTitle: "チャットファイルからインポート",
  fileImportSteps: [
    "WeChat インポートファイルをダウンロード",
    "ファイル転送または自分のチャットへ送信",
    "ミニプログラムで「チャットファイルからインポート」を選び、ファイルを指定",
  ],
  downloadFile: "WeChat インポートファイルをダウンロード",
  downloadFileHint: "ダウンロード後、WeChat のファイル転送へ送信",
  downloadSuccess: "ファイルをダウンロードしました。WeChat のファイル転送へ送信してください。",
  downloadError: "ファイルをダウンロードできませんでした。もう一度お試しください。",
  fileImportPrivacy: "ファイルにはプライバシー保護済みの指標だけが含まれます。信頼できるチャットにのみ送信してください。",
  scanAlternativeTitle: "またはスキャンしてインポート",
  scanAlternativeHint: "このレシートは1つのデータ QR コードに収まります。",
  showDataQr: "データ QR コードを表示",
  showMiniProgramCode: "ミニプログラムのコードへ戻る",
  dataQrTitle: "スキャンしてデータをインポート",
  dataQrHint: "ミニプログラムでスキャンインポートを選んでから、このコードを読み取ってください。",
  dataQrAlt: "現在のレシートデータの QR コード",
  miniProgramAlt: "WeChat ミニプログラムのコード",
  exportMiniProgramLabel: "スキャンしてミニプログラムを開く",
  placeholderLabel: "ミニプログラム",
  placeholderValue: "準備中",
  placeholderAria: "ミニプログラムのコードは準備中です",
  transferNote: "インポートファイルと任意のデータコードには、時間、ターン数、Token、ツール呼び出しなどの統計のみが含まれます。プロンプト、応答本文、コード、プロジェクトパス、ファイル名は含まれません。",
  rollingSummaryNotice: "直近 {hours} 時間は個人履歴専用のローリングサマリーです。AI Work Cooperative の集計には参加しません。集計対象にするには、今日、今週、直近7日間、または特定のセッションを選んでください。",
  customSummaryNotice: "時刻を指定した範囲は個人用サマリーであり、AI Work Cooperative の集計には参加しません。日付単位で指定すると、重複排除できる正規の記録を作成できます。",
  projectScopeTemplate: "選択したプロジェクト · {scope}",
  privacy: "構造化データと WeChat インポートファイルは、このコンピューターに保存されます。あなたがファイルを送信するかデータコードをスキャンするまで、プライバシー保護済みの統計が外部へ送られることはありません。",
};

const COMPENSATION_COPY = {
  "zh-CN": {
    latest: "本单工资",
    session: "本单工资",
    "last-hours": "本段工资",
    "custom-range": "区间工资",
    today: "本日工资",
    "last-7-days": "近七日工资",
    "this-week": "本周工资",
    unit: "AI 工分",
    note: "按轮次、工具调用、Token 和改需求次数娱乐折算，不代表真实费用。",
  },
  en: {
    latest: "SHIFT PAY",
    session: "SHIFT PAY",
    "last-hours": "WINDOW PAY",
    "custom-range": "RANGE PAY",
    today: "TODAY'S PAY",
    "last-7-days": "7-DAY PAY",
    "this-week": "THIS WEEK'S PAY",
    unit: "AI work pts",
    note: "A playful score based on turns, tool calls, Tokens, and interruptions. Not a real charge.",
  },
  ja: {
    latest: "今回の作業ポイント",
    session: "今回の作業ポイント",
    "last-hours": "この時間帯の作業ポイント",
    "custom-range": "期間の作業ポイント",
    today: "今日の作業ポイント",
    "last-7-days": "直近7日間の作業ポイント",
    "this-week": "今週の作業ポイント",
    unit: "AI 作業ポイント",
    note: "ターン数、ツール呼び出し、Token、中断回数から遊び心で算出した値です。実際の料金ではありません。",
  },
};

export function selectWorkProfileId(metrics) {
  const scale = Math.max(1, Number(metrics.activeDayCount || 1));
  if (metrics.interruptions >= 3 * scale) return "change-request-survivor";
  if (metrics.toolCalls >= 40 * scale) return "toolchain-commander";
  if (metrics.tokens.total_tokens >= 500_000 * scale) return "context-devouring-beast";
  if (metrics.completedTurns >= 12 * scale) return "continuous-delivery-machine";
  if (metrics.workDurationMs >= 60 * 60 * 1000 * scale) return "night-shift-companion";
  if (metrics.completedTurns >= 5 * scale) return "steady-progress-partner";
  return "temporary-hire";
}

export function getWorkProfileCopy(profileId, locale = DEFAULT_LOCALE) {
  const profile = WORK_PROFILES[profileId] || WORK_PROFILES["temporary-hire"];
  return profile[SUPPORTED_LOCALES.has(locale) ? locale : DEFAULT_LOCALE];
}

export function getReceiptCopy(locale = DEFAULT_LOCALE) {
  return RECEIPT_COPY[SUPPORTED_LOCALES.has(locale) ? locale : DEFAULT_LOCALE];
}

export function getScopeLabel(scope, locale = DEFAULT_LOCALE, hours = null, options = {}) {
  const copy = getReceiptCopy(locale);
  const scopeKey = scope === "custom-range" && options.rangeKind
    ? `custom-range-${options.rangeKind}`
    : scope;
  const template = copy.scope[scopeKey] || copy.scope[scope] || copy.scope.latest;
  const label = String(template).replaceAll("{hours}", String(hours || 3));
  return options.filterKind === "project"
    ? String(copy.projectScopeTemplate).replaceAll("{scope}", label)
    : label;
}

export function getRollingSummaryNotice(locale = DEFAULT_LOCALE, hours = null) {
  return String(getReceiptCopy(locale).rollingSummaryNotice).replaceAll("{hours}", String(hours || 3));
}

export function getCustomSummaryNotice(locale = DEFAULT_LOCALE) {
  return getReceiptCopy(locale).customSummaryNotice;
}

export function buildCompensation(scope, amount, locale = DEFAULT_LOCALE) {
  const copy = COMPENSATION_COPY[SUPPORTED_LOCALES.has(locale) ? locale : DEFAULT_LOCALE];
  return {
    label: copy[scope] || copy.latest,
    amount: Number(amount || 0),
    unit: copy.unit,
    note: copy.note,
    formula_version: "work_points_v1",
  };
}
